### ISSUE TITLE
confused by args.K*len(args.fname)

### ISSUE THREAD

**Issue by js850** [js850/nested_sampling#9]
in compute_cv.py it calls compute_cv_c with the following signature

```
compute_cv_c(energies, float(P), float(args.K*len(args.fname)), float(Tmin), float(Tmax), nT, float(args.ndof), args.live)
```

I cannot for the life of me figure out why K is multplied by the length of the file name.

I will removed it.  Let me know if I should leave it in.

**Comment by smcantab** [comment]
I think that it is a temporary patch that assumes that all the input files
have the same K size,  hence the total K would be Ktot= K*no of input
files.  It's not really necessary as you can insert the total K by yourself
doing the sum (and this way the script is also more general). I can't think
of a good reason why I did it that way, but I did it,  maybe I was just
being lazy and I didn't want to do the sums since I was always using data
files obtained with the same K :-)

I think that I pointed this out in the help message of the script as a
warning.

Stefano

**Comment by js850** [comment]
oh, right, I forgot fname was a list of file names.  I think i'll still remove it as you suggest.
